version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: ssd_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2F3nVry6
      POSTGRES_DB: SSD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ssd_network

  app:
    image: openjdk:17-jdk-alpine
    container_name: ssd_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/SSD
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2F3nVry6
    ports:
      - "8080:8080"
    volumes:
      - ./target/SSD-0.0.1-SNAPSHOT.jar:/app/SSD-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/app/SSD-0.0.1-SNAPSHOT.jar"]
    networks:
      - ssd_network

volumes:
  postgres_data:

networks:
  ssd_network:
    driver: bridge
